### ISSUE TITLE
Null Pointer exception

### ISSUE THREAD

**Issue by lumsilva** [matheusribeirolima/marvel-app#1]
Ao abrir o app o mesmo ao colocar as chaves ele apresentar o seguinte erro:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.MutableLiveData.postValue(java.lang.Object)' on a null object reference
        at com.marvel.app.home.presentation.HomeViewModel$listCharacters$1.invokeSuspend(HomeViewModel.kt:26)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6128)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by matheusribeirolima** [comment]
Obrigado pelo report @lumsilva mas infelizmente não tive tempo de deixar ele "utilizável", fiz somente uma integração com a API e estruturação de CI e arquitetura do projeto. Espero que nesse fds eu tenha tempo pra dar continuidade.
